export const alumnidata = [
  {
    name: "Alok Ranjan Joshi",
    email: "alokranjanjoshi@gmail.com",
    gender: "male",
    mobile: 9178785362,
    pbatch: 2017,
    branch: "CSE",
    job: "Software Developer",
    location: "Bhubaneswer",
  },
  {
    name: "Aliva Jyoti Joshi",
    email: "alivajyotijoshi@gmail.com",
    gender: "female",
    mobile: 9178785492,
    pbatch: 2020,
    branch: "EE",
    job: "Web Developer",
    location: "Bolangir",
  },
  {
    name: "Lipun Bag",
    email: "baglipun@gmail.com",
    gender: "male",
    mobile: 9178764562,
    pbatch: 2021,
    branch: "ME",
    job: "Android Developer",
    location: "Bangomunda",
  },
  {
    name: "Liza Patra",
    email: "lizapatra222@gmail.com",
    gender: "female",
    mobile: 6374208987,
    pbatch: 2015,
    branch: "CSE",
    job: "Web Developer",
    location: "Bhubaneswer",
  },
  {
    name: "Anamika Pati",
    email: "patianamika@gmail.com",
    gender: "female",
    mobile: 8658785362,
    pbatch: 2017,
    branch: "IT",
    job: "Backend Developer",
    location: "Bhubaneswer",
  },
  {
    name: "Amlan Das",
    email: "amlan456@gmail.com",
    gender: "male",
    mobile: 9834844562,
    pbatch: 2015,
    branch: "MSC",
    job: "Frontend Developer",
    location: "Bhubaneswer",
  },
];
